# Generated by Django 6.0.3 on 2026-03-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=100, verbose_name='Raça')),
                ('data_acolhimento', models.DateField(verbose_name='Data de Acolhimento')),
                ('data_adocao', models.DateField(blank=True, null=True, verbose_name='Data de Adoção')),
                ('status', models.CharField(choices=[('acolhido', 'Acolhido'), ('disponivel', 'Disponível para Adoção'), ('adotado', 'Adotado')], default='acolhido', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('item', 'Item')], max_length=20, verbose_name='Tipo de Doação')),
                ('data', models.DateField(verbose_name='Data da Doação')),
                ('nome_doador', models.CharField(blank=True, help_text='Opcional', max_length=200, verbose_name='Nome do Doador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome_item', models.CharField(max_length=200, verbose_name='Nome do Item')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Doação de Item',
                'verbose_name_plural': 'Doações de Itens',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MoneyDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('item', 'Item')], max_length=20, verbose_name='Tipo de Doação')),
                ('data', models.DateField(verbose_name='Data da Doação')),
                ('nome_doador', models.CharField(blank=True, help_text='Opcional', max_length=200, verbose_name='Nome do Doador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor em reais (R$)', max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Doação em Dinheiro',
                'verbose_name_plural': 'Doações em Dinheiro',
                'ordering': ['-data'],
            },
        ),
    ]
