# Generated by Django 6.0.3 on 2026-05-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zepereira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='instagram_post_url',
            field=models.URLField(blank=True, help_text='Opcional', verbose_name='URL do Post no Instagram'),
        ),
    ]
