# Generated by Django 6.0.5 on 2026-05-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zepereira', '0002_animal_instagram_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea'), ('nao_informado', 'Não informado')], default='nao_informado', max_length=20, verbose_name='Sexo'),
        ),
    ]
